export const HOME    = 0;
export const ROUTE   = 1;
export const SIGNIN  = 2;
export const CALC    = 3;
export const MAP     = 4;
export const PROFILE = 5;
export const SEARCH  = 6;
export const REGISTER= 7;
export const SIGNOUT = 8;
